name: CI Pipeline - Dev Branch

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create __init__.py files
      run: |
        touch src/__init__.py
        touch tests/__init__.py
    
    - name: Verify data exists
      run: |
        echo "Checking for data files..."
        ls -la data/
        ls -la week3/feature_store/ || echo "Week3 feature store not found"
    
    - name: Train model
      run: |
        python src/train.py
    
    - name: Run Data Validation Tests
      run: |
        echo "========================================="
        echo "Running Data Validation Tests"
        echo "========================================="
        pytest tests/test_data_validation.py -v

    - name: Train model
      run: |
        python src.train.py
    
    - name: Run Evaluation Tests
      run: |
        echo "========================================="
        echo "Running Evaluation Tests"
        echo "========================================="
        pytest tests/test_evaluation.py -v