name: CI Pipeline - Main Branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup DVC
      run: |
        dvc remote list
    
    - name: Pull DVC tracked files
      run: |
        dvc pull || echo "No DVC files to pull yet"
    
    - name: Train model if not exists
      run: |
        python src/train.py
    
    - name: Run Data Validation Tests
      run: |
        pytest tests/test_data_validation.py -v
    
    - name: Run Evaluation Tests
      run: |
        pytest tests/test_evaluation.py -v
